// src/Shared/Components/Image.jsx
import { Icons } from "../Models/Icons";

export function Image({ staticImage = null, type = null, imgKey = null, className = null, width = "20px" }) {
  if (staticImage) return <img className={className} src={Icons[staticImage]} alt={staticImage} width={width} />;

  if (type && imgKey) return <img className={className} src={type[imgKey]} alt={imgKey} width={width} />;

  return;
}

// app/components/ImageComponent.vue
<template>
  <ClientOnly>
    <img v-if="staticImg" :src="Icons[staticImg]" :alt="alt" :class="className" />
  </ClientOnly>
</template>

<script setup lang="ts">
import { ClientOnly } from "#components";
import { Icons } from "~/models/Icons";

defineProps<{
  staticImg?: keyof typeof Icons | null;
  alt?: string | undefined;
  className?: string | null;
}>();
</script>
