// src/Shared/Components/Input.jsx
import { useState } from "react";

export function Input({ name = null, id = null, textLabel = null, className = null, initialValue = "", placeholder = null, type = "text" }) {
  const [value, setValue] = useState(initialValue);

  return (
    <>
      <label htmlFor={id}>{textLabel}</label>
      <input id={id} name={name} className={className} placeholder={placeholder} value={value} onChange={(e) => setValue(e.target.value)} type={type} />
    </>
  );
}

// app/components/InputComponent.vue
<template>
  <label v-if="textLabel && id" :for="id">{{ textLabel }}</label>
  <input :id="id" :name="name" :type="type" :placeholder="placeHolder" />
</template>

<script setup lang="ts">
withDefaults(
  defineProps<{
    id?: string;
    name?: string;
    textLabel?: string;
    placeHolder?: string;
    type?: string;
    initialValue?: string;
  }>(),
  {
    type: "text",
    placeHolder: "",
    initialValue: "",
  }
);
</script>
