// app/sections/NavBar/NavBar.vue
<template>
  <nav>
    <ImageComponent staticImg="AppLogoIcon" />
    <div class="navbar__div-search">
      <div class="navbar__div-icon-wrapper">
        <ImageComponent staticImg="SearchIcon" />
      </div>
      <InputComponent placeHolder="Buscar..." />
    </div>
  </nav>
</template>

<script setup lang="js">
import ImageComponent from "~/components/ImageComponent.vue";
import InputComponent from "~/components/InputComponent.vue";
import "./NavBarStyle.scss";
</script>

// src/Sections/NavBar/NavBar.jsx
import { Image } from "../../Shared/Components/Image";
import { Input } from "../../Shared/Components/Input";
import "./NavBarStyle.scss";

export function NavBar() {
  return (
    <>
      <nav>
        <div>
          <Image staticImage={"AppLogoIcon"} width="170px" />
        </div>
        <div className="navbar__div-filter">
          <div>
            <Image staticImage={"SearchIcon"} width="30px" />
          </div>
          <Input placeholder={"Busque uma máquina aqui..."} />
        </div>
      </nav>
    </>
  );
}
